services:
  web:
    build: .
    container_name: sight-words
    expose:
      - "8000"
    networks:
      - web
    env_file:
      - ~/secrets/common.env
    restart: unless-stopped
    volumes:
      - ./progress.db:/app/progress.db:ro

networks:
  web:
    external: true
